4/2.SharedResourceFiles/Globoticket.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Globoticket.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

4/2.SharedResourceFiles/Globoticket.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Globoticket.Web.Pages
{
    public class IndexModel : PageModel
    {
        public string Message = string.Empty;

        public string Title = "Ticket Purchase";

        public Dictionary<int, Category> CategoriesWithPrices = new Dictionary<int, Category>() {
            { 1, new Category("Standing", 33.33) },
            { 2, new Category("Upper Level", 44.44) },
            { 3, new Category("Lower Level", 55.55) },
        };

        public void OnGet()
        {
            string language = HttpContext.Request.Headers["Accept-Language"];
            if (language.StartsWith("de-") || language.StartsWith("de;"))
            {
                Title = "Ticketkauf";
            } else if (language.StartsWith("fr-") || language.StartsWith("fr;"))
            {
                Title = "Achat de billets";
            }
        }

        public void OnPost(DateTime eventdate, int category, int amount)
        {
            var totalAmount = amount * CategoriesWithPrices[category].Price;
            Message = String.Format(
                "You ordered {0} ticket{1} for a total of ${2} for the event on {3}.",
                amount,
                amount > 1 ? "s" : "",
                totalAmount,
                eventdate.ToShortDateString());
        }

        public IActionResult OnGetSetCulture(string cultureName)
        {
            var culture = new RequestCulture(cultureName);
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(culture));

            return RedirectToPage("Index");
        }

        public readonly record struct Category(string Description, double Price);
    }
}

4/2.SharedResourceFiles/Globoticket.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Globoticket.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

4/2.SharedResourceFiles/Globoticket.Web/Pages/Index.cshtml
@page
@using static Globoticket.Web.Pages.IndexModel
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Localization
@using Microsoft.Extensions.Options
@inject IStringLocalizer<SharedResources> Localizer

@inject IOptions<RequestLocalizationOptions> LocalizationOptions

@model IndexModel

@{
    var RequestCultureInfo = HttpContext.Features.Get<IRequestCultureFeature>();
}

<div class="text-center mb-3">
    <h1 class="display-4">@Localizer["TicketPurchase"]</h1>
</div>

<div class="mt-3 mb-3">
@foreach (var culture in LocalizationOptions.Value.SupportedCultures)
{
    <a asp-page-handler="SetCulture" asp-route-cultureName="@culture" class="text-decoration-none">
<span class="badge rounded-pill
        @((culture.ToString() == RequestCultureInfo?.RequestCulture.Culture.ToString()) ?
            "bg-primary" : "bg-info text-dark")">@culture</span>
    </a>
}
</div>

<div class="alert alert-info col-12" role="alert">
    Current culture: @RequestCultureInfo?.RequestCulture.Culture <br>
    Current UI culture: @RequestCultureInfo?.RequestCulture.UICulture
</div>

@if (!string.IsNullOrEmpty(Model.Message)) {
<div class="alert alert-success col-12" role="alert">
    @Model.Message
</div>
} else {
<form class="row g-3" method="post" action="">
    <div class="input-group mb-3">
        <span class="input-group-text bi bi-calendar" id="eventdate-addon"></span>
        <div class="form-floating col-11">
            <input type="date" class="form-control" name="eventdate" id="eventdate" placeholder="Event date" value="@DateTime.Now.ToShortDateString()" aria-label="Event date" aria-describedby="eventdate-addon">
            <label for="eventdate">Event date</label>
        </div>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text bi bi-map" id="category-addon"></span>
        <div class="form-floating col-11">
            <select class="form-select" name="category" id="category" aria-label="Category" aria-describedby="category-addon">
                <option value="">Choose a seat category</option>
                @foreach (KeyValuePair<int, Category> category in Model.CategoriesWithPrices)
                {
                    <option value="@category.Key">@category.Value.Description ($@category.Value.Price)</option>    
                }
            </select>
            <label for="category">Category</label>
        </div>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text bi bi-ticket-detailed" id="amount-addon"></span>
        <div class="form-floating col-11">
            <input type="number" class="form-control" name="amount" id="amount" placeholder="Enter number of tickets" aria-label="Number of tickets" aria-describedby="amount-addon">
            <label for="amount">Number of tickets</label>
        </div>
    </div>

    <div class="col-12">
        <button class="btn btn-primary" type="submit">Order</button>
    </div>
</form>
}

4/2.SharedResourceFiles/Globoticket.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Globoticket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Globoticket.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index"><img src="/images/logo.png"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Globoticket
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>